### ISSUE TITLE
"Error loading node list: An error occurred while sending the request."

### ISSUE THREAD

**Issue by LividBunny** [metal-crow/DaS-PC-MPChan#6]
I just opened DSCM a few days ago and it was working fine...

**Comment by metal-crow** [comment]
It seems the DSCM node list server is down atm, ty for telling me! I'll see about fixing it asap. In the meantime, direct connections should still work.

**Comment by metal-crow** [comment]
Should be fixed now! The server host reported that there was some downtime with the cloud service provider.
